---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: duck1123/dinsro-dev
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password
---
kind: secret
name: username
get:
  path: dockerhub-creds
  name: DOCKERHUB_USERNAME
---
kind: secret
name: password
get:
  path: dockerhub-creds
  name: DOCKERHUB_PASSWORD
