stages:
- name: Publish Builder
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-dev
      buildContext: .
      tag: duck1123/dinsro-dev:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
